const COPY = {
  createPost: {
    hashtagPoolSelector: {
      copy: 'Copy',
      delete: 'Delete',
      toasts: {
        success: {
          copy: 'Hashtags copied to clipboard',
        },
        error: {
          delete: 'Failed to delete hashtag pool. Please try again.',
          copy: 'Failed to copy hashtags to clipboard.',
        },
      },
    },
  },
  socialCalendar: {
    socialCalendar: 'Social Calendar',
    socialCalendarDescription: 'Plan and preview upcoming social media posts',
    layoutDescription:
      'Drag to reorder · Click empty to create · Click post to edit · Double-click to preview',
    addPost: 'Add Post',
    clickToCreate: 'Click to create',
    hoverPostHelperText: 'Click to edit · Double-click to preview · Drag to reorder',
    hoverPublishedPostHelperText: 'Click to edit · Double-click to preview',
    compose: 'Compose',
    layout: 'Layout',
    calendar: 'Calendar',
    platforms: 'Platforms',
    grid: 'Grid',
    quickPost: 'Quick Post',
    templates: 'Templates',
    bulkSchedule: 'Bulk Schedule',
    tagFilter: 'Tags',
    tagFilterPlaceholder: 'Filter by tags',
    noPostsMatchingFilters: 'No posts match the active filters',
    noPostsMatchingFiltersHint: 'Try removing some filters to see posts',
    clearFilters: 'Clear filters',
    allPlatforms: 'All Platforms',
    allStatuses: 'All Statuses',
    platformLabel: 'Platform',
    statusLabel: 'Status',
    sortByPlaceholder: 'Sort by…',
    sortNewest: 'Newest first',
    sortOldest: 'Oldest first',
    sortByStatus: 'By status',
    sortByPlatform: 'By platform',
    sortDefaultOrder: 'Default order',
    noPostsScheduled: 'No posts scheduled',
    noPostsScheduledHint: 'Add your first post to the calendar',
    signOffCalendar: 'Sign Off Calendar',
    signOffApprovedBy: 'Sign Off Approved By',
    signOffDate: 'Sign Off Date',
    approveAllPosts: 'Approve All Posts',
    approverNamePlaceholder: 'Enter approver name...',
    approverNameRequired: 'Please enter approver name',
    cancel: 'Cancel',
    discardChangesTitle: 'Discard changes?',
    discardNewPostDescription:
      'You have unsaved changes. Are you sure you want to start a new post?',
    discardNewPostConfirm: 'Discard & Start New',
    discardViewSwitchDescription:
      'You have unsaved changes in the composer. Are you sure you want to switch views without saving?',
    discardViewSwitchConfirm: 'Discard Changes',
    keepEditing: 'Keep Editing',
    draggedToPastTime:
      "This post's scheduled time is now in the past. Open the post to update the time.",
    swapDatesOnDrag: 'Swap dates of posts when dragging',
    untitled: 'Untitled',
    unscheduled: 'unscheduled',
    toasts: {
      success: {
        swappedDates: (nameA: string, dateB: string, nameB: string, dateA: string) =>
          `Swapped dates: "${nameA}" → ${dateB}, "${nameB}" → ${dateA}`,
      },
      error: {
        reorderPosts: 'Failed to update post order. Please try again.',
        publishedPost: 'Published posts cannot be reordered.',
      },
    },
  },
  calendarPostModal: {
    editPost: 'Edit Post',
    createPost: 'Create Post',
    tags: 'Tags',
    aiAssistant: 'AI Assistant',
    preview: 'Preview',
    compose: 'Compose',
    approvalWorkflow: 'Approval Workflow',
    comments: 'Comments',
    teamFeedback: 'Team Feedback',
    captionPlaceholder: 'Start writing your post here...',
    seePreviewHere: "See your post's preview here",
    yourAccount: 'Your Account',
    justNow: 'Just now',
    captionPreviewPlaceholder: 'Your caption will appear here…',
    dragAndDrop: 'Drag & drop or',
    selectAFile: 'select a file',
    recurringPost: 'Recurring Post',
    recurringEnabled: 'Configure a recurring schedule for this post below.',
    recurringDisabled: 'This post will be scheduled once.',
    repeat: 'repeat',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    endDateOptional: 'End date (optional)',
    schedule: 'Schedule',
    bestTimes: 'Best Times',
    bestTimesForPlatform: 'Best times for {platform} based on typical audience activity:',
    apply: 'Apply →',
    date: 'Date',
    time: 'Time',
    requiresApproval: 'Requires Approval',
    approvalEnabled: 'This post will be sent for team approval before going live.',
    approvalDisabled: 'This post will be scheduled without requiring approval.',
    approvalPermissionTooltip:
      'You do not have permission to change this setting. Please contact an admin for assistance.',
    deletePost: 'Delete Post',
    saveDraft: 'Save Draft',
    draftSaved: 'Saved',
    revertToDraft: 'Revert to Draft',
    revertToDraftTitle: 'Revert to Draft?',
    revertToDraftDescription:
      'This will revert the post to draft status, remove the assigned reviewer, reset priority, and clear the due date and note. The post will need to go through the approval workflow again.',
    revertToDraftConfirm: 'Revert to Draft',
    newPost: 'New Post',
    submitForReview: 'Submit for Review',
    sendForApproval: 'Send for Approval',
    approvalReviewerRequired: 'Please assign a reviewer.',
    approvalPriorityRequired: 'Please select a priority.',
    approvalDueDateRequired: 'Please set a due date.',
    approvalDueDatePast: 'Due date cannot be in the past.',
    approvalDueDateAfterSchedule: 'Review due date must be on or before the scheduled post date.',
    approvalDueDateHint: 'Reviewer has until end of this day.',
    updatePost: 'Update Post',
    schedulePost: 'Schedule Post',
    deleteConfirmTitle: 'Delete Post',
    deleteConfirmDescription:
      'Are you sure you want to delete this post? It will be removed from the following platform(s): {platforms}',
    delete: 'Delete',
    cancel: 'Cancel',
    connectDropboxTitle: 'Connect Dropbox First',
    connectDriveTitle: 'Connect Google Drive First',
    connectDropboxDescription:
      "Dropbox isn't connected in this workspace yet. Open Settings to review the current integrations setup before using Dropbox media here.",
    connectDriveDescription:
      "Google Drive isn't connected in this workspace yet. Open Settings to review the current integrations setup before using Drive media here.",
    openSettings: 'Open Settings',
    notNow: 'Not Now',
    twitterDisplayName: 'Twitter / X',
    whereToPost: 'Where would you like to share this post?',
    whereHasPosted: 'Posted to these platforms:',
    exceededCharLimit: 'Exceeded limit of {limit} characters for {platform}',
    cropTitle: 'Crop Image',
    cropForPlatform: 'Crop for {platform}',
    saveCrop: 'Save Crop',
    resetCrop: 'Reset',
    cropInstructions: 'Drag to reposition or resize. Recommended ratio for {platform} is {ratio}.',
    cropRecommended: '{ratio} recommended',
    cropCustom: 'Custom',
    cropPresets: 'Presets',
    cropShiftHintPrefix: 'Hold',
    cropShiftHintSuffix: 'while resizing to lock the aspect ratio.',
    cropRotateLeft: 'Rotate left',
    cropRotateRight: 'Rotate right',
    cropFlipHorizontal: 'Flip horizontal',
    cropFlipVertical: 'Flip vertical',
    cropSafeZones: 'Safe zones',
    cropSafeZonesTooltip:
      "Safe zones mark the area that stays visible across all placements of this format — e.g. the part of an Instagram Reel that isn't hidden behind UI overlays. Keep key content inside the dashed lines.",
    cropSaved: 'Crop saved — preview updated.',
    cropApplied: 'Crop applied for {platform}',
    cropReset: 'Crop reset for {platform}',
    shiftKey: 'Shift',
    uploadImagesFailed: 'Failed to upload images.',
    uploadVideoFailed: 'Failed to upload video.',
    videoBeforeImages: 'Remove the selected video before adding images.',
    imagesBeforeVideo: 'Remove the selected images before adding a video.',
    mixedMediaDrop: 'Choose either images or one video, not both at the same time.',
    oneVideoOnly: 'Only one video can be attached to a post.',
    scheduledTimeInFuture: 'Scheduled time must be in the future.',
    continueToApproval: 'Continue to Approval',
    saveFailed: 'Failed to save post. Please try again.',
    saveSuccessDraft: 'Draft saved.',
    saveSuccessScheduled: 'Post scheduled.',
    resubmitForReview: 'Resubmit for Review',
    saveSuccessPendingReview: 'Post submitted for review.',
    saveSuccessPendingApproval: 'Post sent for approval.',
    saveSuccessPublished: 'Post published.',
    saveSuccessDefault: 'Post saved.',
  },
  linkInserter: {
    title: 'Insert Link',
    urlLabel: 'URL',
    urlPlaceholder: 'https://example.com',
    displayTextLabel: 'Display text',
    displayTextPlaceholder: 'Display text (optional)',
    insert: 'Insert',
    urlError: 'Please enter a valid URL starting with http:// or https://',
  },
  bufferComposer: {
    tags: 'Tags',
    addPhoto: 'Add Photo',
    addFromLibrary: 'Add from Library',
    library: 'Library',
    removeVideoFirst: 'Remove the selected video before adding images.',
    removeImagesFirst: 'Remove the selected images before adding a video.',
    failedUploadVideo: 'Failed to upload video.',
  },
  mediaUpload: {
    imagesSelected: (count: number, max: number) =>
      `${count}/${max} ${count === 1 ? 'image' : 'images'} selected. Video upload is disabled while images are attached.`,
    videoSelected: '1 video selected. Image upload is disabled while a video is attached.',
    mediaHint: (maxImages: number, imageFormats: string, videoFormats: string) =>
      `Add up to ${maxImages} images (${imageFormats}) or one video (${videoFormats}).`,
  },
  tagSelector: {
    placeholder: 'Add tags…',
    searchPlaceholder: 'Search tags…',
    noResults: 'No tags found.',
    loading: 'Loading…',
    createTag: (name: string) => `Create tag "${name}"`,
    createError: 'Failed to create tag. Please try again.',
    deleteSuccess: (name: string) => `Tag "${name}" deleted.`,
    deleteError: 'Failed to delete tag. Please try again.',
    atLimit: 'Posts can only have 10 tags.',
    deleteTagLabel: (name: string) => `Delete tag ${name}`,
    colorLabel: 'Color',
    createWithColor: 'Create',
  },
  tagPill: {
    // Tag-specific label so screen readers can distinguish between multiple pills.
    removeLabel: (name: string) => `Remove tag ${name}`,
  },
  socialTags: {
    activeTab: 'Active',
    archivedTab: 'Archived',
    archiveSuccess: (name: string) => `"${name}" archived`,
    unarchiveSuccess: (name: string) => `"${name}" unarchived`,
    archiveError: 'Failed to update tag. Please try again.',
    duplicateNameError: 'A tag with this name already exists.',
    noActiveTags: 'No active tags.',
    noArchivedTags: 'No archived tags.',
    postCount: (n: number) => `${n} post${n === 1 ? '' : 's'}`,
    archiveLabel: 'Archive',
    unarchiveLabel: 'Unarchive',
  },
  platformBadges: {
    overflow: (count: number) => `+${count}`,
  },
  hashtagManager: {
    searchPlaceholder: 'Search hashtags...',
    addToFavorites: 'Add to Favorites',
    noPoolsFound: 'No hashtag pools found',
    createFirstPool: 'Create your first pool above',
    delete: 'Delete',
    cancel: 'Cancel',
    deletePoolTitle: 'Delete Hashtag Pool',
    deletePoolConfirm:
      'Are you sure you want to delete this hashtag pool? This action cannot be undone.',
    categoriesTitle: 'Categories',
    allHashtags: 'All Hashtags',
    favorites: 'Favorites',
    uncategorized: 'Uncategorized',
    createPoolTitle: 'Create New Hashtag Pool',
    newCategory: 'New Category',
    hashtagsPlaceholder: 'e.g. #marketing #brand #social (# will be added automatically)',
    addPool: 'Add',
    poolNamePlaceholder: 'Pool name...',
    newCategoryPlaceholder: 'New category name...',
    newCategoryAdd: 'Add',
    newCategoryCancel: 'Cancel',
    createPoolError: 'Failed to create hashtag pool. Please try again.',
  },
  approvalQueueView: {
    reviewer: 'Reviewer',
    notAssigned: 'Not assigned',
    priority: 'Priority',
    notSet: 'Not set',
    dueDate: 'Due Date',
    note: 'Note',
    noNote: 'No note',
  },
  approvalWidget: {
    views: 'Views',
    approved: 'Approved',
    rejectedOrChangesRequested: 'Rejected / Changes Requested',
    noDueDateSet: 'No Due Date Set',
    overdue: 'OVERDUE',
    leftUntilDueDate: 'left until Due Date',
    dueDatePrefix: 'Due Date:',
    postDatePrefix: 'Post Date:',
    noPostDateSet: 'No Post Date Set',
  },
  postApprovalView: {
    postNotFound: 'Post not found.',
    backToAllChannels: 'Back to All Channels',
    backToSocialCalendar: 'Back to Social Calendar',
    mediaRetainedNotice:
      'Media retained for version history — not transferred to the Approved Media Database.',
    activity: 'Activity',
    workflow: 'Workflow',
    editPost: 'Edit Post',
  },
  postCommentThread: {
    emptyTitle: 'No comments yet',
    emptySubtitle: 'Leave feedback or notes for the team.',
    inputPlaceholder: 'Add a comment\u2026 use @ to mention someone',
  },
  approvalActionDrawer: {
    rejectedLabel: 'Reason for Rejection',
    approvedLabel: 'Approval Note',
    changesRequestedLabel: 'Changes Requested',
    rejectedSubmit: 'Reject',
    approvedSubmit: 'Approve',
    changesRequestedSubmit: 'Request Changes',
    placeholder: {
      rejected: 'Explain why this post is being rejected\u2026',
      approved: 'Add an approval note (optional)\u2026',
      changes_requested: 'Describe the changes needed\u2026',
    },
    badge: {
      rejection: 'Rejection',
      approval: 'Approval',
      request_changes: 'Changes Requested',
    },
  },
  general: {
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    update: 'Update',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
  },
  mediaLibraryModal: {
    title: 'Select Media Library Images',
    cancel: 'Cancel',
    searchPlaceholder: 'Search media library images',
    loading: 'Loading media library...',
    empty: 'No image assets found in the Media Library.',
  },
  authError: {
    heading: 'Something went wrong',
    defaultMessage: 'The app failed to load. Please refresh to try again.',
  },
  approvalEmail: {
    untitledPost: 'Untitled post',
    fallbackSubmitter: 'A teammate',
    missingValue: '—',
  },
};

export default COPY;
