const COPY = {
  createPost: {
    hashtagPoolSelector: {
      copy: 'Copy',
      delete: 'Delete',
      toasts: {
        success: {
          copy: 'Hashtags copied to clipboard',
        },
        error: {
          delete: 'Failed to delete hashtag pool. Please try again.',
          copy: 'Failed to copy hashtags to clipboard.',
        },
      },
    },
  },
  socialCalendar: {
    nineGridTitle: '9-Grid Layout',
    nineGridDescription: 'Click empty to create · Click post to edit · Double-click to preview',
    addPost: 'Add Post',
    clickToCreate: 'Click to create',
    hoverPostHelperText: 'Click to edit · Double-click to preview · Drag to reorder',
    hoverPublishedPostHelperText: 'Click to edit · Double-click to preview',
    toasts: {
      error: {
        reorderPosts: 'Failed to update post order. Please try again.',
        publishedPost: 'Published posts cannot be reordered.',
      },
    },
  },
  calendarPostModal: {
    editPost: 'Edit Post',
    createPost: 'Create Post',
    tags: 'Tags',
    aiAssistant: 'AI Assistant',
    preview: 'Preview',
    compose: 'Compose',
    approvalWorkflow: 'Approval Workflow',
    teamFeedback: 'Team Feedback',
    captionPlaceholder: 'Start writing your post here...',
    seePreviewHere: "See your post's preview here",
    yourAccount: 'Your Account',
    justNow: 'Just now',
    captionPreviewPlaceholder: 'Your caption will appear here…',
    dragAndDrop: 'Drag & drop or',
    selectAFile: 'select a file',
    recurringPost: 'Recurring Post',
    repeat: 'repeat',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    endDateOptional: 'End date (optional)',
    schedule: 'Schedule',
    bestTimes: 'Best Times',
    bestTimesForPlatform: 'Best times for {platform} based on typical audience activity:',
    apply: 'Apply →',
    date: 'Date',
    time: 'Time',
    requiresApproval: 'Requires Approval',
    approvalEnabled: 'This post will be sent for team approval before going live.',
    approvalDisabled: 'This post will be scheduled without requiring approval.',
    approvalPermissionTooltip:
      'You do not have permission to change this setting. Please contact an admin for assistance.',
    deletePost: 'Delete Post',
    saveDraft: 'Save Draft',
    submitForReview: 'Submit for Review',
    sendForApproval: 'Send for Approval',
    updatePost: 'Update Post',
    schedulePost: 'Schedule Post',
    deleteConfirmTitle: 'Delete Post',
    deleteConfirmDescription:
      'Are you sure you want to delete this post? It will be removed from the following platform(s): {platforms}',
    delete: 'Delete',
    cancel: 'Cancel',
    connectDropboxTitle: 'Connect Dropbox First',
    connectDriveTitle: 'Connect Google Drive First',
    connectDropboxDescription:
      "Dropbox isn't connected in this workspace yet. Open Settings to review the current integrations setup before using Dropbox media here.",
    connectDriveDescription:
      "Google Drive isn't connected in this workspace yet. Open Settings to review the current integrations setup before using Drive media here.",
    openSettings: 'Open Settings',
    notNow: 'Not Now',
    twitterDisplayName: 'Twitter / X',
    whereToPost: 'Where would you like to share this post?',
    whereHasPosted: 'Posted to these platforms:',
  },
  hashtagManager: {
    searchPlaceholder: 'Search hashtags...',
    addToFavorites: 'Add to Favorites',
    noPoolsFound: 'No hashtag pools found',
    createFirstPool: 'Create your first pool above',
    delete: 'Delete',
    cancel: 'Cancel',
    deletePoolTitle: 'Delete Hashtag Pool',
    deletePoolConfirm:
      'Are you sure you want to delete this hashtag pool? This action cannot be undone.',
    categoriesTitle: 'Categories',
    allHashtags: 'All Hashtags',
    favorites: 'Favorites',
    uncategorized: 'Uncategorized',
    createPoolTitle: 'Create New Hashtag Pool',
    newCategory: 'New Category',
    hashtagsPlaceholder: 'e.g. #marketing #brand #social (# will be added automatically)',
    addPool: 'Add',
  },
};

export default COPY;
